# Day 4 — Pandas: Tabular Data

## 1. Series and DataFrames

Pandas is the primary Python library for working with tabular, spreadsheet-like data.

A `Series` represents one labeled column.

A `DataFrame` represents a complete table containing rows and named columns.

## 2. Loading Data from a CSV File

Pandas uses `read_csv()` to load a CSV file into a DataFrame.

The CSV file should be in the same folder as the Jupyter Notebook, or its correct file path must be provided.

In [9]:
import pandas as pd

df = pd.read_csv("BLNWR.csv")

## 3. Inspecting the Dataset

After loading the dataset, it is important to inspect its structure before performing any analysis.

This includes:
- Viewing the first few rows.
- Checking the number of rows and columns.
- Listing the column names.
- Identifying the data type of each column.

In [17]:
print("First five rows:")
df.head()

First five rows:

,Date,Day,Month,Year,Season,Site,Sample,Subsample,Sample_Position,Trap_size_sq_m,Noels_Alive,Springsnails
0,10/16/2014,16,October,2014,Fall,Bitter Creek,Bitter Creek 1,3,Bank,0.006,0,134
1,10/16/2014,16,October,2014,Fall,Bitter Creek,Bitter Creek 1,1,Mid Channel,0.006,0,800
2,10/16/2014,16,October,2014,Fall,Bitter Creek,Bitter Creek 1,2,Mid Point,0.006,0,1593
3,10/16/2014,16,October,2014,Fall,Bitter Creek,Bitter Creek 2,3,Bank,0.006,0,345
4,10/16/2014,16,October,2014,Fall,Bitter Creek,Bitter Creek 2,1,Mid Channel,0.006,0,429

In [18]:
print("Shape:")
df.shape

Shape:

(720, 12)

In [19]:
print("\nColumns:")
df.columns

Columns:

Index(['Date', 'Day', 'Month', 'Year', 'Season', 'Site', 'Sample', 'Subsample',
       'Sample_Position', 'Trap_size_sq_m', 'Noels_Alive', 'Springsnails'],
      dtype='object')

In [20]:
print("\nData types:")
df.columns.tolist()

Data types:

['Date',
 'Day',
 'Month',
 'Year',
 'Season',
 'Site',
 'Sample',
 'Subsample',
 'Sample_Position',
 'Trap_size_sq_m',
 'Noels_Alive',
 'Springsnails']

In [23]:
print("\nDatatypes:")
df.dtypes

Datatypes:

Date                object
Day                  int64
Month               object
Year                 int64
Season              object
Site                object
Sample              object
Subsample            int64
Sample_Position     object
Trap_size_sq_m     float64
Noels_Alive          int64
Springsnails         int64
dtype: object

In [24]:
print("\nDataset information:")
df.info()

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             720 non-null    object
 1   Day              720 non-null    int64
 2   Month            720 non-null    object
 3   Year             720 non-null    int64
 4   Season           720 non-null    object
 5   Site             720 non-null    object
 6   Sample           720 non-null    object
 7   Subsample        720 non-null    int64
 8   Sample_Position  720 non-null    object
 9   Trap_size_sq_m   720 non-null    float64
 10  Noels_Alive      720 non-null    int64
 11  Springsnails     720 non-null    int64
dtypes: float64(1), int64(5), object(6)
memory usage: 67.6+ KB

## 4. Checking for Missing Values

Before analyzing the data, the dataset should be checked for missing values.

Missing values can affect calculations and statistical analysis, so they should be identified before further processing.

In [26]:
missing_values= df.isnull().sum()

print("Missing values per column: ")
print(missing_values)

Missing values per column:
Date               0
Day                0
Month              0
Year               0
Season             0
Site               0
Sample             0
Subsample          0
Sample_Position    0
Trap_size_sq_m     0
Noels_Alive        0
Springsnails       0
dtype: int64

In [27]:
missing_percentage = (df.isnull().sum()/len(df)) *100

print("Missing-value percentage per column: ")
print(missing_percentage)

Missing-value percentage per column:
Date               0.0
Day                0.0
Month              0.0
Year               0.0
Season             0.0
Site               0.0
Sample             0.0
Subsample          0.0
Sample_Position    0.0
Trap_size_sq_m     0.0
Noels_Alive        0.0
Springsnails       0.0
dtype: float64

In [29]:
average_noels = df["Noels_Alive"].mean()
print("Average Noels_Alive:", average_noels)

Average Noels_Alive: 2.2333333333333334

## 5. Filtering the Dataset

Filtering allows us to select only the rows that satisfy a specific condition.

For this analysis, the dataset is filtered to include observations where the value of `Noels_Alive` is greater than the average.

In [30]:
filtered_df = df[df["Noels_Alive"] > average_noels]
filtered_df.head()

,Date,Day,Month,Year,Season,Site,Sample,Subsample,Sample_Position,Trap_size_sq_m,Noels_Alive,Springsnails
33,7/29/2014,29,July,2014,Summer,Bitter Creek,Bitter Creek 6,3,Bank,0.006,9,28
160,3/3/2015,3,March,2015,Winter,Bitter Creek,Bitter Creek 3,1,Mid Channel,0.003,3,7
360,10/15/2014,15,October,2014,Fall,Sago Springs,Sago Ledge,3,Bank,0.006,27,185
361,10/15/2014,15,October,2014,Fall,Sago Springs,Sago Ledge,1,Mid Channel,0.006,7,46
362,10/15/2014,15,October,2014,Fall,Sago Springs,Sago Ledge,2,Mid Point,0.006,5,28

In [31]:
print("Original number of rows:", df.shape[0])
print("Filtered number of rows:", filtered_df.shape[0])
filtered_df[["Noels_Alive", "Springsnails"]].describe()

Original number of rows: 720
Filtered number of rows: 139

       Noels_Alive  Springsnails
count   139.000000    139.000000
mean     10.575540     63.978417
std      10.270951     79.487167
min       3.000000      0.000000
25%       5.000000     14.500000
50%       7.000000     34.000000
75%      12.000000     76.500000
max      69.000000    383.000000

In [32]:
season_average = df.groupby("Season")["Noels_Alive"].mean()
print("Average Noels_Alive by season:")
print(season_average)

Average Noels_Alive by season:
Season
Fall      2.683333
Spring    2.756944
Summer    2.477778
Winter    1.305556
Name: Noels_Alive, dtype: float64

In [33]:
season_summary = df.groupby("Season").agg({
    "Noels_Alive": "mean",
    "Springsnails": "mean"
})

print(season_summary)

        Noels_Alive  Springsnails
Season
Fall       2.683333     88.333333
Spring     2.756944     47.187500
Summer     2.477778     72.483333
Winter     1.305556     27.282407